### ISSUE TITLE
So... how?

### ISSUE THREAD

**Issue by steven4547466** [Agadar/NationStates-Telegrammer-Client#11]
I just came across this while looking for a client and it said simple, but I have no idea on how to open it, I downloaded everything from https://github.com/Agadar/NationStates-Telegrammer-Client/archive/master.zip and I cant find anything to open, I have Java, but still there no opening things, so I'm just confused at how I get this to open so I get the UI

**Comment by steven4547466** [comment]
I found something I could open now, but it says this 
![screenshot_20180530_163426](https://user-images.githubusercontent.com/23726534/40746076-5cd9e35c-6427-11e8-9cc7-2f512bdb2327.png)

**Comment by Agadar** [comment]
You're not supposed to download the .zip file. Those are the uncompiled source files. You're supposed to download the .jar file.

**Comment by Agadar** [comment]
Closed due to lack of activity.
