### ISSUE TITLE
[Suggestion] Filters save upon exit of program

### ISSUE THREAD

**Issue by nickkuro** [Agadar/NationStates-Telegrammer-Client#4]
Hi, @Agadar 

As the title states, could you please implement the saving of filters upon exit of the program and have them show up, ready to go, at the start of the program?

Thank you,

Phoenix Coalition
(nickkuro)

**Comment by Agadar** [comment]
It's a good suggestion. I'll see about adding it in v.1.5.0.

**Comment by nickkuro** [comment]
Thank you!

**Comment by Agadar** [comment]
Added since v.1.5.0.
